"""email table added

Revision ID: 648019037038
Revises: 
Create Date: 2026-08-10 23:36:22.773707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648019037038'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_email', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('user_email')

    # ### end Alembic commands ###
